version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: .dockerfile
    container_name: tanksai-server-${NUM}
    networks:
      - public_network
    volumes:
      - sqlite_data:/app/data
    ports:
      - "${PORT}:${PORT}"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  game:
    build:
      context: ./game
      dockerfile: .dockerfile
    container_name: tanksai-game-${NUM}
    networks:
      - private_network
    volumes:
      - sqlite_data:/app/data
    restart: "no"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  sqlite_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data

networks:
  private_network:
    driver: bridge
    internal: true  # Эта сеть блокирует доступ к интернету
  public_network:
    driver: bridge   # Обычная сеть с доступом к интернету